services:
  tcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cplusplus_management_server
    ports:
      - "9999:9999"
    volumes:
      - server_data:/app
    restart: unless-stopped

volumes:
  server_data: